//
//  NewsfeedWorker.swift
//  VkFeedExample
//
//  Created by Станислав Шияновский on 10/5/19.
//  Copyright (c) 2019 Станислав Шияновский. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public class NewsfeedWorker {
  
    private var authService: AuthService
    private var networking: Networking
    private var fetcher: DataFetcher
    
    private var feedResponse: FeedResponse?
    private var revealedPostIds = [Int]()
    private var newFromInProcess: String?
    
    public init() {
        self.authService = AuthService.shared
        self.networking = NetworkService(authService)
        self.fetcher = NetworkDataFetcher(networking)
    }
    
    public func getUser(completion: @escaping (UserResponse?) -> ()) {
        fetcher.getUser { (userResponse) in
            completion(userResponse)
        }
    }
    
    public func getFeed(completion: @escaping ([Int], FeedResponse) -> ()) {
        fetcher.getFeed(nextBatchFrom: nil) { [weak self] (feed) in
            self?.feedResponse = feed
            guard let feedResponse = self?.feedResponse else { return }
            completion(self!.revealedPostIds, feedResponse)
        }
    }
    
    public func revealPostIds(forPostId postId: Int, completion: @escaping ([Int], FeedResponse) -> ()) {
        revealedPostIds.append(postId)
        guard let feedResponse = self.feedResponse else { return }
        completion(revealedPostIds, feedResponse)
    }
    
    public func getNextBatch(completion: @escaping ([Int], FeedResponse) -> ()) {
        newFromInProcess = feedResponse?.nextFrom
        fetcher.getFeed(nextBatchFrom: newFromInProcess) { [weak self] (feed) in
            guard let feed = feed else { return }
            guard self?.feedResponse?.nextFrom != feed.nextFrom else { return }
            
            if self?.feedResponse == nil {
                self?.feedResponse = feed
            } else {
                self?.feedResponse?.items.append(contentsOf: feed.items)
                
                var profiles = feed.profiles
                if let oldProfiles = self?.feedResponse?.profiles {
                    let oldProfilesFiletered = oldProfiles.filter({ oldProfile -> Bool in
                        !feed.profiles.contains(where: { $0.id == oldProfile.id })
                    })
                    profiles.append(contentsOf: oldProfilesFiletered)
                }
                self?.feedResponse?.profiles = profiles
                
                var groups = feed.groups
                if let oldGroups = self?.feedResponse?.groups {
                    let oldGroupsFiletered = oldGroups.filter({ oldGroup -> Bool in
                        !feed.groups.contains(where: { $0.id == oldGroup.id })
                    })
                    groups.append(contentsOf: oldGroupsFiletered)
                }
                self?.feedResponse?.groups = groups
                
                self?.feedResponse?.nextFrom = feed.nextFrom
            }
            
            guard let feedResponse = self?.feedResponse else { return }
            completion(self!.revealedPostIds, feedResponse)
        }
    }
}
