//
//  NewsfeedModels.swift
//  VkFeedExample
//
//  Created by Станислав Шияновский on 10/5/19.
//  Copyright (c) 2019 Станислав Шияновский. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public enum Newsfeed {
  // MARK: Use cases
  
  public enum Model {
    public struct Request {
        public enum RequestType {
            case getNewsFeed
        }
    }
    public struct Response {
        public enum ResponseType {
            case presentNewsFeed(feed: FeedResponse)
        }
    }
    public struct ViewModel {
        public enum ViewModelType {
            case displayNewsfeed(feedViewModel: FeedViewModel)
        }
    }
  }
}

public struct FeedViewModel {
    public struct Cell: FeedCellViewModel {
        public var iconUrlString: String
        public var name: String
        public var date: String
        public var text: String?
        public var likes: String?
        public var comments: String?
        public var shares: String?
        public var views: String?
    }
    
    let cells: [Cell]
}
