//
//  NewsfeedInteractor.swift
//  VkFeedExample
//
//  Created by Станислав Шияновский on 10/5/19.
//  Copyright (c) 2019 Станислав Шияновский. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public protocol NewsfeedBusinessLogic {
    func makeRequest(request: Newsfeed.Model.Request.RequestType)
}

public protocol NewsfeedDataStore {
    //var name: String { get set }
}

public class NewsfeedInteractor: NewsfeedBusinessLogic, NewsfeedDataStore {
    
    public var presenter: NewsfeedPresentationLogic?
    private var worker: NewsfeedWorker?
    private var fetcher: DataFetcher = NetworkDataFetcher(NetworkService())
    
    // MARK: Do something
    public func makeRequest(request: Newsfeed.Model.Request.RequestType) {
        worker = NewsfeedWorker()
        worker?.doSomeWork()
        
        switch request {
        case .getNewsFeed:
            fetcher.getFeed { [weak self] (feedResponse) in
                guard
                    let `self` = self,
                    let feedResponse = feedResponse else { return }
                self.presenter?.presentData(response: .presentNewsFeed(feed: feedResponse))
            }
        }
    }
}
