//
//  NewsfeedModels.swift
//  VkFeedExample
//
//  Created by Станислав Шияновский on 10/5/19.
//  Copyright (c) 2019 Станислав Шияновский. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public enum Newsfeed {
  // MARK: Use cases
  
  public enum Model {
    public struct Request {
        public enum RequestType {
            case some
            case getFeed
        }
    }
    public struct Response {
        public enum ResponseType {
            case some
            case presentNewsFeed
        }
    }
    public struct ViewModel {
        public enum ViewModelType {
            case some
            case displayNewsfeed
        }
    }
  }
}
