//
//  NewsfeedPresenter.swift
//  VkFeedExample
//
//  Created by Станислав Шияновский on 10/5/19.
//  Copyright (c) 2019 Станислав Шияновский. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public protocol NewsfeedPresentationLogic {
    func presentData(response: Newsfeed.Model.Response.ResponseType)
}

public class NewsfeedPresenter: NewsfeedPresentationLogic {
    
    public weak var viewController: NewsfeedDisplayLogic?
    
    // MARK: Do something
    public func presentData(response: Newsfeed.Model.Response.ResponseType) {
        
        switch response {
        case .some:
            print(".some Presenter")
        case .presentNewsFeed:
            print(".presentNewsFeed Presenter")
            viewController?.displayData(viewModel: .displayNewsfeed)
        }
    }
}
